### PR TITLE
constraint was not being applied on cori

### PR DESCRIPTION
**Pull request by jedwards4b**
Changes to get the pio_update2 branch running on cori.

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
@ryanlong1004 please hold off on merging until @jedwards4b is finished - there might be additional fixes coming in.  For some reason we cannot get this to draft status.

**Comment by jedwards4b** [comment]
@ryanlong1004 can you explain to me how this works on cori without this change?

**Comment by jedwards4b** [comment]
The error I am getting from tests is 
PMPI_Type_size(119): MPI_Type_size(MPI_DATATYPE_NULL) failed
PMPI_Type_size(69).: Datatype for argument datatype is a null datatype

But everywhere in pio I protect calls to MPI_Type_size with:
```
    if (mpi_type == MPI_DATATYPE_NULL)
        (*iodesc)->mpitype_size = 0;
    else
        if ((mpierr = MPI_Type_size((*iodesc)->mpitype, &(*iodesc)->mpitype_size)))
            return check_mpi(ios, NULL, mpierr, __FILE__, __LINE__);
```
I have traced the problem to the darshan module on cori but I don't see where modules are controlled by the code in this repo.

**Comment by jedwards4b** [comment]
@theurich I found the issue (nothing to do with mpich) - its the darshan module on cori, darshan is a tool that nersc uses to monitor IO.

**Comment by theurich** [comment]
@jedwards4b very good! Should we explicitly unload the darshan module for this configuration? Or do they offer a version that works?

**Comment by jedwards4b** [comment]
Yes I am testing explicitly unloading darshan now and I am filing a bug report with NERSC - I will copy esmf_core on the bug report.

**Comment by jedwards4b** [comment]
I have yet to get the test through the queue to confirm that unloading darshan will work with full esmf tests, I did confirm with pio standalone tests.   I have also updated the cori.yaml file with a section which includes the latest default compiler and mpich version and uses parallel-netcdf and netcdf-hdf5parallel.

**Comment by jedwards4b** [comment]
Is it possible to specify one netcdf module for mpiuni and another for mpich?   
Is there a way to specify a pnetcdf module?

**Comment by theurich** [comment]
@jedwards4b I am not the expert, @ryanlong1004 would know better. The way I understand it though, the netcdf module is compiler specific, not mpi specific. Look at the hera.yaml, what we do there is break out different mpi implementations across differently named intel or gfortran compiler options (those are just strings), so we can load different netcdf modules.

**Comment by jedwards4b** [comment]
@theurich thank you, that example helped.  For the record [here](https://github.com/darshan-hpc/darshan/issues/698) is the issue opened on Darshan.

**Comment by jedwards4b** [comment]
```
Found 13647 exhaustive multi-processor unit tests, 13647 passed and 0 failed.
Found 49 multi-processor system tests, 49 passed and 0 failed.
Found 80 multi-processor examples, 80 passed and 0 failed.
Found 49 multi-processor system tests, 49 passed and 0 failed.
Found 80 multi-processor examples, 80 passed and 0 failed.
Found 13647 exhaustive multi-processor unit tests, 13647 passed and 0 failed.
```

It looks like turning off Darshan did the trick, now I'm going to try updating modules and adding pnetcdf.

**Comment by theurich** [comment]
@jedwards4b this PR is still a draft. Is it ready to move into review? If so I think it would need to be by @rsdunlapiv for the cori constraint part, and by @ryanlong1004 in general since it is testing infrastructure.

**Comment by jedwards4b** [comment]
I still have it in review because I wanted to provide an update of modules used on cori.  But cray has messed up the modules for netcdf and pnetcdf again.   The issue is that nc-config and pnetcdf-config give wrong answers and so we either need to get them fixed or not use them when building ESMF.

**Comment by jedwards4b** [comment]
If you want to just have the working tests with the old modules I can revert some of the changes that I made in cori.yaml

**Comment by jedwards4b** [comment]
Ready for review and merge.

**Review by ryanlong1004 — CHANGES_REQUESTED** [review]
@jedwards4b build-test.py is deprecated.

The change should be made in test_esmf.py.

You'd also need to add a carriage return to have each command on a separate line.

The line that you're adding would be added to all configuration files.  You could add the line to a config file using the extra_env_vars.

**Comment by jedwards4b** [comment]
Wow - could no one have informed me that I was using the wrong script?   Why is the deprecated script still present?  The change in cori.yaml is all that is really needed here, so if I fixed a script that you no longer need then no changes to this PR should be required - should they?  Note that I reverted the change 
to add pnetcdf - I'll leave that as an exercise for you.

**Comment by rsdunlapiv** [comment]
@ryanlong1004 please remove any deprecated script and/or make it obvious what is deprecated so that this does not confuse anyone else.  Some time ago I asked for some documentation on setting up and running the test framework.  That would have been helpful in this case.

**Review by ryanlong1004 — APPROVED** [review]

**Comment by theurich** [comment]
@ryanlong1004 @jedwards4b @rsdunlapiv - All Cori combos failed last night!

**Comment by theurich** [comment]
It's the pnetcdf-config that is not found: https://github.com/esmf-org/esmf-test-artifacts/blob/f723c6614455f4dda8a74f83f843056f81d1f347/jedwards_pio_update2/cori/intel/19.0.3/O/mpiuni/none/out/build.log#L2

**Comment by rsdunlapiv** [comment]
@ryanlong1004 the ball is in your court to address the pnetcdf-config issue on Cori.

**Comment by ryanlong1004** [comment]
@jedwards4b I don't have visibility to the modules available on Cori.  From your code changes, it looks like you trying to load 'pnetcdf' as a module.  Do you have a version?

I'm assuming the use of the 'pnetcdf-config' is as a gateway to pass config options to callers since from the docs it says it's a reporting tool.  

Is that correct or do flags need to be added to the assignment?

**Comment by jedwards4b** [comment]
No there was no mention of pnetcdf in the final update of this pr.  If so
remove it.

**Pull request merged**
