### PR TITLE
Update hera.yaml

### PR DESCRIPTION
**Pull request by ryanlong1004**
Explicit cmake.

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
@ryanlong1004 the extramodule for cmake is needed for all compilers.  Here you have only added this to intel.  Please also add to gfortran and PGI.

**Review by rsdunlapiv — CHANGES_REQUESTED** [review]
Add CMake module to all compilers in the hera.yaml

**Comment by theurich** [comment]
It's good to have cmake added to all combos now. However, note that even when it was just added to intel (last night), it did NOT fix the build issue with intel.
In fact, we now have a new issue on hera/intel that we did NOT have before: hera/intel/mpiuni built the library fine yesterday, but today it is failing. 
Folks that make changes, either on the test environment, or the library code itself need to keep an eye on the nightly tests. It should not go unnoticed that today's pio_update2 results look worse than yesterday's. For this branch I think the responsibility is primarily on @ryanlong1004 and @jedwards4b.

**Comment by jedwards4b** [comment]
[Is this todays build?](https://github.com/esmf-org/esmf-test-artifacts/blob/2add6b52656c8f20a17ca298d94b3f3327025021/jedwards_pio_update2/hera/gfortran/9.2.0/O/openmpi/3.1.4/out/test.log#L84)
The NetCDF version is still 2.7.2

**Comment by rsdunlapiv** [comment]
I think I see the issue with the cmake module.  It was added here to Hera/intel 18:
https://github.com/esmf-org/esmf-test-scripts/commit/c726124fb81e74505666ef2c76363da801009b01

However, it was added too deeply in the YAML below the "18.0.4:" key.   Instead, it should be added under the "intel:" key one level up in the YAML.  

Note the position of the "extramodule:" in [acorn.yaml](https://github.com/esmf-org/esmf-test-scripts/blob/main/config/acorn.yaml).   

@ryanlong1004 please move these "extramodule: cmake" commands up one level in hera.yaml.  Then please confirm when the tests run again that the new module was in fact loaded for each of the compiler combinations.

**Comment by jedwards4b** [comment]
[In this one.](https://github.com/esmf-org/esmf-test-artifacts/blob/e6488b1ec15b128a677c2bb63c0189db95e831a4/jedwards_pio_update2/discover/intel/2020/O/mpt/2.17/out/test.log)   The c++ and fortran compilers are intel but the c compiler is gcc and it's trying to set intel based flags - can you change the c compiler to use icc?

**Comment by jedwards4b** [comment]
[Netcdf version 4.7.2](https://github.com/esmf-org/esmf-test-artifacts/blob/9ca443589eff1e569352a6b73e9e49ddf66841bf/jedwards_pio_update2/hera/gfortran/9.2.0/g/openmpi/3.1.4/out/test.log#L73)

**Comment by jedwards4b** [comment]
[CMAKE version 2](https://github.com/esmf-org/esmf-test-artifacts/blob/cf827af46d8db4dd6b5eeb1876ca3eaae3355752/jedwards_pio_update2/hera/intel/18.0.4/O/intelmpi/2018.4.274/out/test.log#L39)

**Comment by jedwards4b** [comment]
[Needs to be changed](https://github.com/esmf-org/esmf-test-scripts/pull/68/files#diff-e6cfc8021dddf588d91e4d2fe2f6833f125945deaf95f7dc360d814c78dc2550L31)

**Comment by ryanlong1004** [comment]
@rsdunlapiv 

https://github.com/esmf-org/esmf-test-scripts/commit/a0b058c6c4a441a42dd495f6c03080d9c7a1b27a

**Pull request merged**
